package com.chlobot.platform.app.task;

public enum AgentEventType {
    TASK_CREATED,
    STATUS_CHANGED,
    PLAN_GENERATED,
    CLARIFICATION_REQUIRED,
    TOOL_CONFIRMATION_REQUIRED,
    TOOL_CALL_APPROVED,
    TOOL_CALL_REJECTED,
    TOOL_CALL_STARTED,
    TOOL_CALL_COMPLETED,
    PROGRESS,
    PARTIAL_RESULT,
    WARNING,
    ERROR,
    COMPLETED,
    CANCELLED,
    RETRY_REQUESTED
}
